In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 5]])

In [3]:
arr.shape

(2, 4)

In [4]:
arr.ndim

2

In [5]:
arr.size

8

In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
a + 1

array([2, 3, 4, 5])

In [8]:
2 * a

array([2, 4, 6, 8])

In [9]:
a**2

array([ 1,  4,  9, 16])

In [10]:
np.power(a, 2)

array([ 1,  4,  9, 16], dtype=int32)

In [11]:
np.sum(a)

10

In [12]:
a.sum()

10

In [13]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [14]:
x.sum(axis=0)

array([3, 3])

In [15]:
x.sum(axis=1)

array([2, 4])

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,1],[4,3]])

a == b

array([[False, False],
       [False, False]])

In [17]:
np.array_equal(a, b)

False